/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('./components/ui/button/index').Button
  const DropdownMenu: typeof import('./components/ui/dropdown-menu/index').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/index').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu/index').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu/index').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu/index').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu/index').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu/index').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/index').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/index').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/index').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/index').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu/index').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/index').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/index').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/index').DropdownMenuTrigger
  const EffectScope: typeof import('vue').EffectScope
  const Input: typeof import('./components/ui/input/index').Input
  const SIDEBAR_COOKIE_MAX_AGE: typeof import('./components/ui/sidebar/utils').SIDEBAR_COOKIE_MAX_AGE
  const SIDEBAR_COOKIE_NAME: typeof import('./components/ui/sidebar/utils').SIDEBAR_COOKIE_NAME
  const SIDEBAR_KEYBOARD_SHORTCUT: typeof import('./components/ui/sidebar/utils').SIDEBAR_KEYBOARD_SHORTCUT
  const SIDEBAR_WIDTH: typeof import('./components/ui/sidebar/utils').SIDEBAR_WIDTH
  const SIDEBAR_WIDTH_ICON: typeof import('./components/ui/sidebar/utils').SIDEBAR_WIDTH_ICON
  const SIDEBAR_WIDTH_MOBILE: typeof import('./components/ui/sidebar/utils').SIDEBAR_WIDTH_MOBILE
  const Separator: typeof import('./components/ui/separator/index').Separator
  const Sheet: typeof import('./components/ui/sheet/index').Sheet
  const SheetClose: typeof import('./components/ui/sheet/index').SheetClose
  const SheetContent: typeof import('./components/ui/sheet/index').SheetContent
  const SheetDescription: typeof import('./components/ui/sheet/index').SheetDescription
  const SheetFooter: typeof import('./components/ui/sheet/index').SheetFooter
  const SheetHeader: typeof import('./components/ui/sheet/index').SheetHeader
  const SheetTitle: typeof import('./components/ui/sheet/index').SheetTitle
  const SheetTrigger: typeof import('./components/ui/sheet/index').SheetTrigger
  const Sidebar: typeof import('./components/ui/sidebar/index').Sidebar
  const SidebarContent: typeof import('./components/ui/sidebar/index').SidebarContent
  const SidebarFooter: typeof import('./components/ui/sidebar/index').SidebarFooter
  const SidebarGroup: typeof import('./components/ui/sidebar/index').SidebarGroup
  const SidebarGroupAction: typeof import('./components/ui/sidebar/index').SidebarGroupAction
  const SidebarGroupContent: typeof import('./components/ui/sidebar/index').SidebarGroupContent
  const SidebarGroupLabel: typeof import('./components/ui/sidebar/index').SidebarGroupLabel
  const SidebarHeader: typeof import('./components/ui/sidebar/index').SidebarHeader
  const SidebarInput: typeof import('./components/ui/sidebar/index').SidebarInput
  const SidebarInset: typeof import('./components/ui/sidebar/index').SidebarInset
  const SidebarMenu: typeof import('./components/ui/sidebar/index').SidebarMenu
  const SidebarMenuAction: typeof import('./components/ui/sidebar/index').SidebarMenuAction
  const SidebarMenuBadge: typeof import('./components/ui/sidebar/index').SidebarMenuBadge
  const SidebarMenuButton: typeof import('./components/ui/sidebar/index').SidebarMenuButton
  const SidebarMenuItem: typeof import('./components/ui/sidebar/index').SidebarMenuItem
  const SidebarMenuSkeleton: typeof import('./components/ui/sidebar/index').SidebarMenuSkeleton
  const SidebarMenuSub: typeof import('./components/ui/sidebar/index').SidebarMenuSub
  const SidebarMenuSubButton: typeof import('./components/ui/sidebar/index').SidebarMenuSubButton
  const SidebarMenuSubItem: typeof import('./components/ui/sidebar/index').SidebarMenuSubItem
  const SidebarProvider: typeof import('./components/ui/sidebar/index').SidebarProvider
  const SidebarRail: typeof import('./components/ui/sidebar/index').SidebarRail
  const SidebarSeparator: typeof import('./components/ui/sidebar/index').SidebarSeparator
  const SidebarTrigger: typeof import('./components/ui/sidebar/index').SidebarTrigger
  const Skeleton: typeof import('./components/ui/skeleton/index').Skeleton
  const Toaster: typeof import('./components/ui/sonner/index').Toaster
  const Tooltip: typeof import('./components/ui/tooltip/index').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip/index').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip/index').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip/index').TooltipTrigger
  const axios: typeof import('axios').default
  const buttonVariants: typeof import('./components/ui/button/index').buttonVariants
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineProps: typeof import('vue').defineProps
  const effectScope: typeof import('vue').effectScope
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const provideSidebarContext: typeof import('./components/ui/sidebar/utils').provideSidebarContext
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const sidebarMenuButtonVariants: typeof import('./components/ui/sidebar/index').sidebarMenuButtonVariants
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useMouse: typeof import('@vueuse/core').useMouse
  const useMyFetch: typeof import('@vueuse/core').useFetch
  const useSidebar: typeof import('./components/ui/sidebar/utils').useSidebar
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ButtonVariants } from './components/ui/button/index'
  import('./components/ui/button/index')
  // @ts-ignore
  export type { SidebarMenuButtonProps } from './components/ui/sidebar/SidebarMenuButtonChild.vue'
  import('./components/ui/sidebar/SidebarMenuButtonChild.vue')
  // @ts-ignore
  export type { SidebarProps, SidebarMenuButtonVariants } from './components/ui/sidebar/index'
  import('./components/ui/sidebar/index')
}
